name: CI/CD - Spring Boot

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build-and-test:
    name: Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build do projeto
        run: mvn clean install

      - name: Executar testes
        run: mvn test

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: echo "Docker instalado por padrão no runner"

      - name: Build Docker image
        run: |
          mvn clean package
          docker build -t yas-spring-app .